//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_WebDesign_Main.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ERP_WebDesign_MasterModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ERP_WebDesign_MasterModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP_WebDesign_Main.Resources.ERP_WebDesign_MasterModelResource", typeof(ERP_WebDesign_MasterModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist material code.
        /// </summary>
        public static string CODE_EXIST_ALERTMESSAGE {
            get {
                return ResourceManager.GetString("CODE_EXIST_ALERTMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material code.
        /// </summary>
        public static string CODI_CODE {
            get {
                return ResourceManager.GetString("CODI_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string CODI_GROUP {
            get {
                return ResourceManager.GetString("CODI_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codification id.
        /// </summary>
        public static string CODI_ID {
            get {
                return ResourceManager.GetString("CODI_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string CODI_ITEM {
            get {
                return ResourceManager.GetString("CODI_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        public static string CODI_RACK {
            get {
                return ResourceManager.GetString("CODI_RACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        public static string CODI_SPEC {
            get {
                return ResourceManager.GetString("CODI_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select all the required dropdown fields..
        /// </summary>
        public static string CODI_VALIDATION_DDMESSAGE {
            get {
                return ResourceManager.GetString("CODI_VALIDATION_DDMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODI-.
        /// </summary>
        public static string CODIFICATION_ID_PREFIX {
            get {
                return ResourceManager.GetString("CODIFICATION_ID_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Wage Frequency.
        /// </summary>
        public static string DAILYWAGE_FREQUENCY {
            get {
                return ResourceManager.GetString("DAILYWAGE_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide daily wage frequency.
        /// </summary>
        public static string DAILYWAGE_FREQUENCY_NOTBLANK {
            get {
                return ResourceManager.GetString("DAILYWAGE_FREQUENCY_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group code.
        /// </summary>
        public static string GROUP_CODE {
            get {
                return ResourceManager.GetString("GROUP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide group code.
        /// </summary>
        public static string GROUP_CODE_NOTBLANK {
            get {
                return ResourceManager.GetString("GROUP_CODE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group display name.
        /// </summary>
        public static string GROUP_DISPLAYNAME {
            get {
                return ResourceManager.GetString("GROUP_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide group display name.
        /// </summary>
        public static string GROUP_DISPLAYNAME_NOTBLANK {
            get {
                return ResourceManager.GetString("GROUP_DISPLAYNAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group id.
        /// </summary>
        public static string GROUP_ID {
            get {
                return ResourceManager.GetString("GROUP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide group.
        /// </summary>
        public static string GROUP_ID_NOTBLANK {
            get {
                return ResourceManager.GetString("GROUP_ID_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRP-.
        /// </summary>
        public static string GROUP_ID_PREFIX {
            get {
                return ResourceManager.GetString("GROUP_ID_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation date.
        /// </summary>
        public static string INSTALL_DATE {
            get {
                return ResourceManager.GetString("INSTALL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide machine installation date.
        /// </summary>
        public static string INSTALL_DATE_NOTBLANK {
            get {
                return ResourceManager.GetString("INSTALL_DATE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code.
        /// </summary>
        public static string ITEM_CODE {
            get {
                return ResourceManager.GetString("ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide item code.
        /// </summary>
        public static string ITEM_CODE_NOTBLANK {
            get {
                return ResourceManager.GetString("ITEM_CODE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        public static string ITEM_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ITEM_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide item display name.
        /// </summary>
        public static string ITEM_DISPLAYNAME_NOTBLANK {
            get {
                return ResourceManager.GetString("ITEM_DISPLAYNAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string ITEM_ID {
            get {
                return ResourceManager.GetString("ITEM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEM-.
        /// </summary>
        public static string ITEMS_ID_PREFIX {
            get {
                return ResourceManager.GetString("ITEMS_ID_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Address.
        /// </summary>
        public static string LABOUR_ADDR {
            get {
                return ResourceManager.GetString("LABOUR_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour address.
        /// </summary>
        public static string LABOUR_ADDR_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_ADDR_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Name.
        /// </summary>
        public static string LABOUR_CONTACT {
            get {
                return ResourceManager.GetString("LABOUR_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour contact.
        /// </summary>
        public static string LABOUR_CONTACT_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_CONTACT_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Daily Wage.
        /// </summary>
        public static string LABOUR_DAILYWAGE {
            get {
                return ResourceManager.GetString("LABOUR_DAILYWAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide daily wage.
        /// </summary>
        public static string LABOUR_DAILYWAGE_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_DAILYWAGE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Hourly Rate.
        /// </summary>
        public static string LABOUR_HOURLYRATE {
            get {
                return ResourceManager.GetString("LABOUR_HOURLYRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour hourly rate.
        /// </summary>
        public static string LABOUR_HOURLYRATE_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_HOURLYRATE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour ID.
        /// </summary>
        public static string LABOUR_ID {
            get {
                return ResourceManager.GetString("LABOUR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Name.
        /// </summary>
        public static string LABOUR_Name {
            get {
                return ResourceManager.GetString("LABOUR_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour name.
        /// </summary>
        public static string LABOUR_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_NAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Role.
        /// </summary>
        public static string LABOUR_ROLE {
            get {
                return ResourceManager.GetString("LABOUR_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour role.
        /// </summary>
        public static string LABOUR_ROLE_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_ROLE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Shift.
        /// </summary>
        public static string LABOUR_SHIFT {
            get {
                return ResourceManager.GetString("LABOUR_SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour shift.
        /// </summary>
        public static string LABOUR_SHIFT_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_SHIFT_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Skill Sets.
        /// </summary>
        public static string LABOUR_SKILLSET {
            get {
                return ResourceManager.GetString("LABOUR_SKILLSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour skill sets.
        /// </summary>
        public static string LABOUR_SKILLSET_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_SKILLSET_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Standard Working Hour.
        /// </summary>
        public static string LABOUR_STDWORKINGHR {
            get {
                return ResourceManager.GetString("LABOUR_STDWORKINGHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide labour standard working hour.
        /// </summary>
        public static string LABOUR_STDWORKINGHR_NOTBLANK {
            get {
                return ResourceManager.GetString("LABOUR_STDWORKINGHR_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Address.
        /// </summary>
        public static string LOCATION_ADDR {
            get {
                return ResourceManager.GetString("LOCATION_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide location address.
        /// </summary>
        public static string LOCATION_ADDR_NOTBLANK {
            get {
                return ResourceManager.GetString("LOCATION_ADDR_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LOCATION_NAME {
            get {
                return ResourceManager.GetString("LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide location name.
        /// </summary>
        public static string LOCATION_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("LOCATION_NAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine description.
        /// </summary>
        public static string MACHINE_DESC {
            get {
                return ResourceManager.GetString("MACHINE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide mechine description.
        /// </summary>
        public static string MACHINE_DESC_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_DESC_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine ID.
        /// </summary>
        public static string MACHINE_ID {
            get {
                return ResourceManager.GetString("MACHINE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine life.
        /// </summary>
        public static string MACHINE_LIFE {
            get {
                return ResourceManager.GetString("MACHINE_LIFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide machine life.
        /// </summary>
        public static string MACHINE_LIFE_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_LIFE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string MACHINE_Name {
            get {
                return ResourceManager.GetString("MACHINE_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide machine name.
        /// </summary>
        public static string MACHINE_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_NAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil required.
        /// </summary>
        public static string MACHINE_OILREQUIRED {
            get {
                return ResourceManager.GetString("MACHINE_OILREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide oil required for the machine.
        /// </summary>
        public static string MACHINE_OILREQUIRED_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_OILREQUIRED_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power required for the machine .
        /// </summary>
        public static string MACHINE_POWERREQUIRED {
            get {
                return ResourceManager.GetString("MACHINE_POWERREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide power required for the machine.
        /// </summary>
        public static string MACHINE_POWERREQUIRED_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_POWERREQUIRED_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard output quantity.
        /// </summary>
        public static string MACHINE_STANDARDOUTPUTQTY {
            get {
                return ResourceManager.GetString("MACHINE_STANDARDOUTPUTQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide standard output quantity.
        /// </summary>
        public static string MACHINE_STANDARDOUTPUTQTY_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_STANDARDOUTPUTQTY_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard output unit.
        /// </summary>
        public static string MACHINE_STANDARDOUTPUTUNIT {
            get {
                return ResourceManager.GetString("MACHINE_STANDARDOUTPUTUNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide standard output unit.
        /// </summary>
        public static string MACHINE_STANDARDOUTPUTUNIT_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_STANDARDOUTPUTUNIT_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine running time.
        /// </summary>
        public static string MACHINE_STANDARDRUNNINGTIME {
            get {
                return ResourceManager.GetString("MACHINE_STANDARDRUNNINGTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide standard running time.
        /// </summary>
        public static string MACHINE_STANDARDRUNNINGTIME_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_STANDARDRUNNINGTIME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine warranty period.
        /// </summary>
        public static string MACHINE_WARRANTYPERIOD {
            get {
                return ResourceManager.GetString("MACHINE_WARRANTYPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide machine warranty period.
        /// </summary>
        public static string MACHINE_WARRANTYPERIOD_NOTBLANK {
            get {
                return ResourceManager.GetString("MACHINE_WARRANTYPERIOD_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Description.
        /// </summary>
        public static string PROCESS_DESC {
            get {
                return ResourceManager.GetString("PROCESS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide process description.
        /// </summary>
        public static string PROCESS_DESC_NOTBLANK {
            get {
                return ResourceManager.GetString("PROCESS_DESC_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string PROCESS_ID {
            get {
                return ResourceManager.GetString("PROCESS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string PROCESS_Name {
            get {
                return ResourceManager.GetString("PROCESS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide process name.
        /// </summary>
        public static string PROCESS_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("PROCESS_NAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description.
        /// </summary>
        public static string PRODUCT_DESC {
            get {
                return ResourceManager.GetString("PRODUCT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide product description.
        /// </summary>
        public static string PRODUCT_DESC_NOTBLANK {
            get {
                return ResourceManager.GetString("PRODUCT_DESC_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product id.
        /// </summary>
        public static string PRODUCT_ID {
            get {
                return ResourceManager.GetString("PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRD-.
        /// </summary>
        public static string PRODUCT_ID_PREFIX {
            get {
                return ResourceManager.GetString("PRODUCT_ID_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide product name.
        /// </summary>
        public static string PRODUCT_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack code.
        /// </summary>
        public static string RACK_CODE {
            get {
                return ResourceManager.GetString("RACK_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide rack code.
        /// </summary>
        public static string RACK_CODE_NOTBLANK {
            get {
                return ResourceManager.GetString("RACK_CODE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack display name.
        /// </summary>
        public static string RACK_DISPLAYNAME {
            get {
                return ResourceManager.GetString("RACK_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide rack display name.
        /// </summary>
        public static string RACK_DISPLAYNAME_NOTBLANK {
            get {
                return ResourceManager.GetString("RACK_DISPLAYNAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack id.
        /// </summary>
        public static string RACK_ID {
            get {
                return ResourceManager.GetString("RACK_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RACK-.
        /// </summary>
        public static string RACK_ID_PREFIX {
            get {
                return ResourceManager.GetString("RACK_ID_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string SITE_Name {
            get {
                return ResourceManager.GetString("SITE_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide site name.
        /// </summary>
        public static string SITE_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("SITE_NAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification code.
        /// </summary>
        public static string SPEC_CODE {
            get {
                return ResourceManager.GetString("SPEC_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide code.
        /// </summary>
        public static string SPEC_CODE_NOTBLANK {
            get {
                return ResourceManager.GetString("SPEC_CODE_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification details.
        /// </summary>
        public static string SPEC_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SPEC_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide specification details.
        /// </summary>
        public static string SPEC_DISPLAYNAME_NOTBLANK {
            get {
                return ResourceManager.GetString("SPEC_DISPLAYNAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide group.
        /// </summary>
        public static string SPEC_GROUPID_NOTBLANK {
            get {
                return ResourceManager.GetString("SPEC_GROUPID_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification id.
        /// </summary>
        public static string SPEC_ID {
            get {
                return ResourceManager.GetString("SPEC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEC-.
        /// </summary>
        public static string SPEC_ID_PREFIX {
            get {
                return ResourceManager.GetString("SPEC_ID_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide item.
        /// </summary>
        public static string SPEC_ITEMID_NOTBLANK {
            get {
                return ResourceManager.GetString("SPEC_ITEMID_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Process description.
        /// </summary>
        public static string SUBPROCESS_DESC {
            get {
                return ResourceManager.GetString("SUBPROCESS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide sub process description.
        /// </summary>
        public static string SUBPROCESS_DESC_NOTBLANK {
            get {
                return ResourceManager.GetString("SUBPROCESS_DESC_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Process ID.
        /// </summary>
        public static string SUBPROCESS_ID {
            get {
                return ResourceManager.GetString("SUBPROCESS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Process Name.
        /// </summary>
        public static string SUBPROCESS_NAME {
            get {
                return ResourceManager.GetString("SUBPROCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide sub process name.
        /// </summary>
        public static string SUBPROCESS_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("SUBPROCESS_NAME_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Description.
        /// </summary>
        public static string Tool_DESC {
            get {
                return ResourceManager.GetString("Tool_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide tool description.
        /// </summary>
        public static string Tool_DESC_NOTBLANK {
            get {
                return ResourceManager.GetString("Tool_DESC_NOTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool ID.
        /// </summary>
        public static string Tool_ID {
            get {
                return ResourceManager.GetString("Tool_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Name.
        /// </summary>
        public static string Tool_NAME {
            get {
                return ResourceManager.GetString("Tool_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide tool name.
        /// </summary>
        public static string Tool_NAME_NOTBLANK {
            get {
                return ResourceManager.GetString("Tool_NAME_NOTBLANK", resourceCulture);
            }
        }
    }
}
