//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_WebDesign_Main.Model_Entity_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExceptionLogger
    {
        public int EXCEPTIONID { get; set; }
        public string EXCEPTIONMESSAGE { get; set; }
        public string EXCEPTIONSTACKTRACE { get; set; }
        public string EXCEPTIONSOURCE { get; set; }
        public Nullable<System.DateTime> LOGTIME { get; set; }
        public string USERID { get; set; }
    }
}
