//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_WebDesign_Main.Model_Entity_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ShiftMaster
    {
        public string ShiftID { get; set; }
        public string ShiftName { get; set; }
        public Nullable<System.DateTime> ShiftStartTime { get; set; }
        public Nullable<System.DateTime> ShiftEndTime { get; set; }
        public string ShiftDesc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
