//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_WebDesign_Main.Model_Entity_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_JobMaster
    {
        public string SITE { get; set; }
        public string JOBID { get; set; }
        public string JOBNAME { get; set; }
        public string SUBPROCESSID { get; set; }
        public string DETAILS { get; set; }
        public string DEPT { get; set; }
        public Nullable<int> JOBREQ { get; set; }
        public Nullable<int> POWERREQ { get; set; }
        public Nullable<int> STANDARDOUTPUT { get; set; }
        public Nullable<int> STANDARDTIME { get; set; }
    }
}
