//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_WebDesign_Main.Model_Entity_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesOrder
    {
        public string SalesOrderID { get; set; }
        public Nullable<System.DateTime> SalesOrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> Qty { get; set; }
        public string OrderStatus { get; set; }
        public string ProductID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual tbl_ProductMaster tbl_ProductMaster { get; set; }
    }
}
