//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_WebDesign_Main.Model_Entity_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Codification
    {
        public string CodificationID { get; set; }
        public string CodificationCode { get; set; }
        public string ItemID { get; set; }
        public string GroupID { get; set; }
        public string SpecificationID { get; set; }
        public string RackID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual tbl_Groups tbl_Groups { get; set; }
        public virtual tbl_Items tbl_Items { get; set; }
        public virtual tbl_Rack tbl_Rack { get; set; }
        public virtual tbl_Specification tbl_Specification { get; set; }
    }
}
